### ISSUE TITLE
Add initial screenshots

### ISSUE THREAD

**Issue by mnurzia** [illinoisjackson/context-menu-maker#1]
![demo](https://cloud.githubusercontent.com/assets/7797957/23379972/018fb536-fd07-11e6-8fc2-0787d84af43f.png)

![example](https://cloud.githubusercontent.com/assets/7797957/23379902/abb01cc8-fd06-11e6-9575-155931b27e4d.png)

**Comment by diVineProportion** [comment]
so if I run 
```
name: 'random-settings'
title: 'Settings'
exists: [^allfiles]
tree:
    defrag:
        title: 'BLK Unpacker'
        icon: 
            handler: 'exefile'
            executable: 'I:\WarThunder\icon.ico'
        action: '"C:\Program Files (PE)\wt-tools\blk_unpack.exe" --format strict_blk %1'
```
i get 
```
PS C:\WINDOWS\system32> python.exe C:\Users\diVine\Downloads\context-menu-maker-master\main.py C:\Users\diVine\Downloads\context-menu-maker-master\examples\simple.yml run
C:\Users\diVine\Downloads\context-menu-maker-master\contextdocparser.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.documentObject = yaml.load(document)
Python WNDPROC handler failed
```

YAML depreciated warning, and a WNDPROC error. Is it possible to pass %1?
