### ISSUE TITLE
YAML depreciated warning, and a WNDPROC error. Is it possible to pass %1?

### ISSUE THREAD

**Issue by diVineProportion** [illinoisjackson/context-menu-maker#2]
so if I run 
```
name: 'random-settings'
title: 'Settings'
exists: [^allfiles]
tree:
    defrag:
        title: 'BLK Unpacker'
        icon: 
            handler: 'exefile'
            executable: 'I:\WarThunder\icon.ico'
        action: '"C:\Program Files (PE)\wt-tools\blk_unpack.exe" --format strict_blk %1'
```
i get 
```
PS C:\WINDOWS\system32> python.exe C:\Users\diVine\Downloads\context-menu-maker-master\main.py C:\Users\diVine\Downloads\context-menu-maker-master\examples\simple.yml run
C:\Users\diVine\Downloads\context-menu-maker-master\contextdocparser.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.documentObject = yaml.load(document)
Python WNDPROC handler failed
```

YAML depreciated warning, and a WNDPROC error. Is it possible to pass %1?
